### ISSUE TITLE
Possible bug in calculation of SOS

### ISSUE THREAD

**Issue by barnabywalker** [mkborregaard/nodiv#4]
There's possibly a discrepancy in how SOS is calculated in the package and how the paper describes the calculation.

In the paper the calculation is given as:
`SOS = (SR1 - SR2) / 2`

However, it looks like SOS is calculated in the function `parent_representation` in `Prepare_result_object.R` with this line:
`return(rowMeans(cbind(rep_matrix[,desc1row], 1-rep_matrix[, desc2row])))`

Which would mean SOS is calculated by:
`SOS = (SR1 - 1 - SR2) / 2`

I've tested it with the `coquettes` dataset and it looks like it's biasing all SOS values +0.5, so when two clades have equal SR values SOS is 0.5.

Is this the intended behaviour?

**Comment by mkborregaard** [comment]
Hi, thanks for the reporting - it's at least definitely unfortunate that the code is quite different from what's in the paper. It's been a little while since I've last been over this code, but I'll have a look within the next few days.

**Comment by mkborregaard** [comment]
@barnabywalker you're absolutely right :-O That is indeed very unfortunate - the `1` is an error. I wonder how many results this has botched down the way... :scream:

**Comment by barnabywalker** [comment]
I think it only affects the SOS values though, so shouldn't mess results up too badly (it definitely didn't make a huge difference to my results).

Removing the `1` will affect the GND values quite badly though - the p-values used to calculate it will be between -0.5 and 0.5 instead of 0 and 1. Maybe there needs to be two separate functions for calculating the SOS of a node and the r-val of a node?

**Comment by mkborregaard** [comment]
Ah, my fix was a bit quick I see.

**Comment by mkborregaard** [comment]
It appears my tests are incomplete and did not catch this. I'll just add some more tests for the relevant metrics before changing any more. OTOH I'd be surprised if I'd need different functions.
Sorry, I know it's a bit unsettling but it's a while since I had a serious look at this code; I'm almost exclusively using my Julia port of the package ATM (https://github.com/EcoJulia/SpatialEcology.jl) but the node-based stuff is not ported yet.

**Comment by mkborregaard** [comment]
Thanks for your clear feedback! I think you're right nothing very major has been thrown off by this, but it's good to have it fixed. I'll push a new version to CRAN in a day or two. I also managed to increase the test coverage by quite a bit, so there should be fewer surprises in the future.

**Comment by barnabywalker** [comment]
Thank you for getting back about it so quickly! I think I was getting a bit confused about the rval thing, so this has helped as well.
